# -*- coding: utf-8 -*-
"""File Handling AssignmentDay 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8DvRF8L9yyyRx8fhBpL27NmeYOgcV1X
"""

"""Scenario
You are developing a Product Inventory System for a shopping application. Each product contains Product ID, Product Name, Category, Price, and Quantity.
"""
#Q1.Write Products into CSV File ,Create products.csv and write header and product data using csv.writer().

import csv
import json
csv_products = [
    [101, "Laptop", "Electronics", 75000, 10],
    [102, "Mouse", "Accessories", 800, 50],
    [103, "Keyboard", "Accessories", 1500, 30]]

with open("products.csv", "w", newline="") as file:
  writer = csv.writer(file)
  writer.writerow(["ID", "Name", "Category", "Price", "Quantity"])
  writer.writerows(csv_products)
print("CSV file created Successfully")

#Q2.Read Data from CSV File
print("\nReading CSV File:")

with open("products.csv", "r") as file:
    reader = csv.reader(file)

    for row in reader:
        print(row)

# Delete Product where id == 103
updated_products = []

with open("products.csv", "r") as file:
    reader = csv.reader(file)

    for row in reader:
        # Keep header row
        if row[0] == "ID":
            updated_products.append(row)

        # Keep rows except ID 103
        elif row[0] != "103":
            updated_products.append(row)

# Rewrite CSV file
with open("products.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(updated_products)

print("\nProduct with ID 103 deleted from CSV.")

# Display Products with Price > 5000

print("\nProducts with Price Greater than 5000:")

with open("products.csv", "r") as file:
    reader = csv.reader(file)

    next(reader)  # Skip header

    for row in reader:
        if int(row[3]) > 5000:
            print(row)

json_products = [
    {"id": 101, "name": "Laptop", "category": "Electronics", "price": 75000, "quantity": 10},
    {"id": 102, "name": "Mouse", "category": "Accessories", "price": 800, "quantity": 50},
    {"id": 103, "name": "Keyboard", "category": "Accessories", "price": 1500, "quantity": 30},
    {"id": 104, "name": "Mobile", "category": "Electronics", "price": 25000, "quantity": 15},
    {"id": 105, "name": "Headphones", "category": "Accessories", "price": 2000, "quantity": 20}
]
# Write Products into JSON File
with open("products.json", "w") as file:
    json.dump(json_products, file, indent=4)

print("\nJSON file created successfully.")

# Read Data from JSON File
print("\nReading JSON File:")

with open("products.json", "r") as file:
    data = json.load(file)

    for product in data:
        print(product)

# Delete Product where id == 102
with open("products.json", "r") as file:
    data = json.load(file)

updated_data = [product for product in data if product["id"] != 102]

with open("products.json", "w") as file:
    json.dump(updated_data, file, indent=4)

print("\nProduct with ID 102 deleted from JSON.")

# Update Laptop Quantity to 25
with open("products.json", "r") as file:
    data = json.load(file)

for product in data:
    if product["name"] == "Laptop":
        product["quantity"] = 25

with open("products.json", "w") as file:
    json.dump(data, file, indent=4)

print("\nLaptop quantity updated to 25.")

# Display Electronics Products Only

print("\nElectronics Products:")

with open("products.json", "r") as file:
    data = json.load(file)

    for product in data:
        if product["category"] == "Electronics":
            print(product)

# Append New Product to CSV


new_product_csv = [106, "Monitor", "Electronics", 12000, 12]

with open("products.csv", "a", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(new_product_csv)

print("\nNew product appended to CSV.")

# Append New Product to JSON
new_product_json = {
    "id": 106,
    "name": "Monitor",
    "category": "Electronics",
    "price": 12000,
    "quantity": 12
}

with open("products.json", "r") as file:
    data = json.load(file)

data.append(new_product_json)

with open("products.json", "w") as file:
    json.dump(data, file, indent=4)

print("\nNew product appended to JSON.")