# -*- coding: utf-8 -*-
"""Function arrays Day 3 Assignment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQNi6qJCXh5GQHzxsweymGDmdIS-icxP
"""

# Function to calculate sum of all elements in a list

def array_sum(numbers):
    total = 0

    for num in numbers:
        total += num

    return total

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

result = array_sum(numbers)

print("Sum of all elements:", result)

# Function to find the largest element in a list
def find_maximum(numbers):
    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num

    return largest

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

result = find_maximum(numbers)

print("Largest element:", result)

# Function to count even numbers in a list
def count_even_numbers(numbers):
    count = 0

    for num in numbers:
        if num % 2 == 0:
            count += 1

    return count

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

result = count_even_numbers(numbers)

print("Number of even elements:", result)

def reverse_array(numbers):
    reversed_list = []

    for i in range(len(numbers) - 1, -1, -1):
        reversed_list.append(numbers[i])

    return reversed_list

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

result = reverse_array(numbers)

print("Original List:", numbers)
print("Reversed List:", result)

# Function to search an element in a list

def search_element(numbers, target):
    for i in range(len(numbers)):
        if numbers[i] == target:
            return i

    return -1
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

element = 90

result = search_element(numbers, element)

if result != -1:
    print(f"Element {element} found at index {result}")
else:
    print("Element not found")

# Function to check whether a list is palindrome

def is_palindrome(numbers):
    reversed_list = numbers[::-1]

    if numbers == reversed_list:
        return True
    else:
        return False
numbers = [1, 2, 3, 2, 1]

result = is_palindrome(numbers)

if result:
    print("The list is a Palindrome.")
else:
    print("The list is not a Palindrome.")

# Function to find the second largest number

def second_largest(numbers):
    largest = second = float('-inf')

    for num in numbers:
        if num > largest:
            second = largest
            largest = num
        elif num > second and num != largest:
            second = num

    return second

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

result = second_largest(numbers)

print("Second Largest Number:", result)

# Function to find duplicate elements in a list

def find_duplicates(numbers):
    duplicates = []

    for num in numbers:
        if numbers.count(num) > 1 and num not in duplicates:
            duplicates.append(num)

    return duplicates

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

result = find_duplicates(numbers)

print("Duplicate Elements:", result)