# -*- coding: utf-8 -*-
"""Matplotlib Assignment Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127lsyzOOcdwQHGUsbLMUJuFWWY2OqWN_
"""

# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt

medical_data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Medicine_Distributed': [1200, 1500, 1800, 1700, 2100, 2500],
    'Hospital_Orders': [30, 45, 50, 48, 60, 75],
    'Delivery_Time': [5, 4, 6, 5, 3, 2],
    'Revenue': [50000, 65000, 72000, 70000, 85000, 95000]
}

df = pd.DataFrame(medical_data)

# Q1: Create a line chart showing medicine distribution over months

plt.plot(df['Month'], df['Medicine_Distributed'])

plt.title("Medicine Distribution Over Months")
plt.xlabel("Month")
plt.ylabel("Medicine Distributed")

plt.show()
plt.plot(df['Month'], df['Medicine_Distributed'])
plt.title("Medicine Distribution Over Months")
plt.xlabel("Month")
plt.ylabel("Medicine Distributed")
plt.show()

# Q2: Create a line chart for monthly revenue growth

plt.plot(df['Month'], df['Revenue'])

plt.title("Monthly Revenue Growth")
plt.xlabel("Month")
plt.ylabel("Revenue")

plt.show()
plt.plot(df['Month'], df['Revenue'])
plt.title("Monthly Revenue Growth")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.show()

# Q3: Create multiple line charts for Medicine_Distributed and Hospital_Orders
plt.plot(df['Month'], df['Medicine_Distributed'], label='Medicine Distributed')
plt.plot(df['Month'], df['Hospital_Orders'], label='Hospital Orders')

plt.title("Medicine Distribution vs Hospital Orders")
plt.xlabel("Month")
plt.ylabel("Values")
plt.legend()
plt.show()

# Q4: Add markers, grid, title and axis labels

plt.plot(df['Month'], df['Medicine_Distributed'],
         marker='o', linestyle='-')

plt.title("Medicine Distribution")
plt.xlabel("Month")
plt.ylabel("Medicine Distributed")
plt.grid(True)

plt.show()

# Q5: Create a vertical bar chart for hospital orders by month
plt.bar(df['Month'], df['Hospital_Orders'])

plt.title("Hospital Orders by Month")
plt.xlabel("Month")
plt.ylabel("Orders")

plt.show()

# Q6: Create a horizontal bar chart for revenue by month
plt.barh(df['Month'], df['Revenue'])

plt.title("Revenue by Month")
plt.xlabel("Revenue")
plt.ylabel("Month")

plt.show()

# Q7: Create a grouped bar chart comparing Medicine_Distributed and Hospital_Orders
import numpy as np

x = np.arange(len(df['Month']))
width = 0.4

plt.bar(x-width/2,
        df['Medicine_Distributed'],
        width,
        label='Medicine')

plt.bar(x+width/2,
        df['Hospital_Orders'],
        width,
        label='Orders')

plt.xticks(x, df['Month'])

plt.title("Medicine vs Hospital Orders")
plt.xlabel("Month")
plt.ylabel("Values")
plt.legend()

plt.show()

# Q8: Add labels, legends and chart titles
plt.bar(df['Month'],
        df['Hospital_Orders'],
        label='Orders')

plt.title("Hospital Orders")
plt.xlabel("Month")
plt.ylabel("Orders")
plt.legend()

plt.show()

# Q9: Create a scatter plot for Hospital_Orders vs Revenue
plt.scatter(df['Hospital_Orders'],
            df['Revenue'])

plt.title("Hospital Orders vs Revenue")
plt.xlabel("Hospital Orders")
plt.ylabel("Revenue")

plt.show()

# Q10: Create a scatter plot for Delivery_Time vs Revenue

plt.scatter(df['Delivery_Time'],
            df['Revenue'])

plt.title("Delivery Time vs Revenue")
plt.xlabel("Delivery Time")
plt.ylabel("Revenue")

plt.show()

# Q11: Create a scatter plot for Medicine_Distributed vs Hospital_Orders
plt.scatter(df['Medicine_Distributed'],
            df['Hospital_Orders'])

plt.title("Medicine Distributed vs Hospital Orders")
plt.xlabel("Medicine Distributed")
plt.ylabel("Hospital Orders")

plt.show()

plt.pie(df['Medicine_Distributed'],
        labels=df['Month'])

plt.title("Medicine Distribution Percentage")

plt.show()

plt.pie(df['Revenue'],
        labels=df['Month'])

plt.title("Revenue Contribution by Month")

plt.show()

explode = [0,0,0,0,0,0.2]

plt.pie(df['Revenue'],
        labels=df['Month'],
        explode=explode,
        autopct='%1.1f%%')

plt.title("Revenue Contribution Percentage")

plt.show()

