# -*- coding: utf-8 -*-
"""Python Operators Day 2 Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tv3R0JB_BQPeY_zRp3YjY3FuXbrdxIHd
"""

"""Q1. Given a product price of 12,500, apply a discount of 10% and then add 18% GST. Calculate the final payable amount."""

P = 12500
d = 10
GST = 18
Discount = P - (P * d / 100)
gst = Discount + (Discount * GST / 100)
print(gst)

"""Q2. A customer places an order worth 8,000. Check whether the order qualifies for free delivery (free delivery if order value ≥ 10,000)."""


Order = 8000
if Order >= 10000:
  print("Free Delivery Available")
else:
  print("Free Delivery Not Available")

"""Q3. You have two orders with amounts 45,000 and 72,000. Find which order has the higher value using comparison operators."""

O1 = 45000
O2 = 72000
if O1 > O2 :
  print("45000")
else:
  print("72000")

"""Q4. An order is eligible for a special offer if order amount is greater than 50,000 AND payment mode is 'Online'. Write logic using logical operators."""


Amount = int(input("Enter the Amount: "))
pay = input("")
if Amount > 50000 and pay == "Online":
  print("Eligible for Special Offer")
else:
  print("Not eliginle ")

"""Q5. Given total items = 37 and box capacity = 6, calculate how many full boxes are required and how many items remain."""


T = 37
Capacity = 6
Full = T // Capacity
Box = T % Capacity
print("Total Box Needed: ",Full)
print("Remaining Item:", Box)

"""Q6. Write a program to classify an order:
- Amount > 100,000 → Premium Order
- Amount between 50,000 and 100,000 → Standard Order
- Else → Basic Order"""

Amount = int(input("Enter the Amount:"))
if Amount > 100000:
  print("Premium Order")
elif Amount > 50000 and Amount < 100000:
  print("Standard Order")
else:
  print("Basic Order")

"""Q7. A product stock count is given. If stock is 0, print 'Out of Stock'. Otherwise, print 'Available'."""

Stock = 4
if Stock > 0:
  print("Availale")
else:
  print("Out of Stock")

"""Q8. A customer is eligible for a return only if the order is delivered AND return request is raised within 7 days. Write the conditional logic."""


Orderstatus = input("Enter the Order Status: ")
Returndays = int(input("Enter the Returndays: "))
if Orderstatus == "Delivered" and Returndays <= 7:
  print("Eligible for Return")
else:
  print("Not Eligible for Return")

"""Q9. Given a list of order amounts, print only the orders greater than 50,000."""

List = [12000,52000,70000,49000,50000,89000]
for i in range(len(List)):
  if List[i] > 50000:
    print(List[i])

"""Q10. You have a list of products with prices. Apply 5% discount to each product and print the updated prices."""


p = ["apple","orange","grapes","banana"]
c = [200,150,400,300]
discount_c = []
for i in range(len(c)):
  discount = c[i] - c[i] * 5 / 100
  discount_c.append(discount)
print(discount_c)

"""Q11. Iterate through a list of orders and count how many orders are above 1,00,000."""

orders = [100001,99000,150000,300000,99999,100000]
for i in range(len(orders)):
  if orders[i] > 100000:
    print(orders[i])

"""Q12. Simulate payment retry logic where the system retries payment a maximum of 3 times if payment fails."""

max_retry = 3
attempts = 0
while attempts<max_retry:
  attempts += 1
  print("Payment attempt:",attempts)
  print("Payment Failed Retry")
print("Payment failed after 3 attempts.")

"""Q13. Write a program that keeps checking order status until status becomes 'Delivered' or maximum 5 attempts are reached."""

attempt = 0
max_attempts = 5
order_status = ""
while attempt < max_attempts:
  order_status = input("Enter the Order Status:")
  attempt+=1
  if order_status == "Delivered":
    print("Order delivered successfully")
    break
  else:
    print("Checking again aattempt:",attempt)
if order_status != "Delivered":
  print("Maximum attempts reached and order not delivered yet")

"""Q14. Inventory restock check: Keep checking stock level every iteration and stop when stock becomes greater than 100."""


stock = 50
while stock <= 100:
  print("Current Stock: ",stock)
  stock = int(input("Enter the new stock level:"))
print('Stock is sufficient now:',stock)

"""Q15. You are given a list of orders with order_id and amount.
- Skip cancelled orders
- Classify remaining orders as Premium or Regular
- Count total premium orders"""

orders = [
    {"order_id": 101, "amount": 8000, "status": "Delivered"},
    {"order_id": 102, "amount": 15000, "status": "Delivered"},
    {"order_id": 103, "amount": 12000, "status": "Cancelled"},
    {"order_id": 104, "amount": 5000, "status": "Delivered"},
    {"order_id": 105, "amount": 20000, "status": "Delivered"}
]

premium_count = 0  # counter for premium orders

for order in orders:
    if order["status"] == "Cancelled":
        continue  # skip cancelled orders

    if order["amount"] > 10000:
        print("Order", order["order_id"], "is Premium")
        premium_count += 1
    else:
        print("Order", order["order_id"], "is Regular")

print("Total Premium Orders:", premium_count)